name: Common Workflow
on:
  workflow_call:
    inputs:
      # Environment:
      #   required: true
      #   type: environment
      User:
        type: string
        required: true

jobs:
  common-steps:
    runs-on: ubuntu-latest
    # environment: ${{ inputs.Environment }}

    steps:
    - name: Common step1
      run: |
        echo "Common User: ${{ inputs.User }}"