name: Common Workflow
on:
  workflow_call:
    inputs:
      Environment:
        required: true
        type: string
      User:
        type: string
        required: true
      name:
        type: string

jobs:
  common-steps:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Environment }}

    steps:
    - name: Common step1
      run: |
        echo "Common User: ${{ inputs.User }}"
        echo "Common Environment: ${{ inputs.Environment }}"
        echo "Common Environment: ${{ inputs.name }}"